# Generated by Django 5.1.3 on 2024-11-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_marca_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
