# Generated by Django 5.1.3 on 2024-11-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
